import { useCallback, useEffect, useRef, useState } from 'react';

export interface InsertedRow {
  tempId: string;
  fields: Record<string, string | null>;
  autoFields: Set<string>;
}

interface ModifiedCell {
  value: string | null;
  originalValue: unknown;
}

export interface PendingChanges {
  modifiedCells: Map<string, ModifiedCell>;
  deletedRows: Set<number>;
  insertedRows: InsertedRow[];
  modifyCell: (rowIndex: number, colName: string, newValue: string | null, originalValue: unknown) => void;
  revertCell: (rowIndex: number, colName: string) => void;
  markRowsDeleted: (indices: number[]) => void;
  unmarkRowDeleted: (index: number) => void;
  addInsertedRow: (columns: string[], autoGeneratedCols: Set<string>) => void;
  removeInsertedRow: (tempId: string) => void;
  updateInsertedRowField: (tempId: string, col: string, value: string | null) => void;
  toggleInsertedRowAuto: (tempId: string, col: string) => void;
  revertAll: () => void;
  clearAfterSubmit: () => void;
  changeCount: number;
  hasChanges: boolean;
  isCellModified: (rowIndex: number, colName: string) => boolean;
  isRowDeleted: (rowIndex: number) => boolean;
  getCellValue: (rowIndex: number, colName: string) => string | null | undefined;
}

let nextTempId = 0;

export function usePendingChanges(resetKey: string): PendingChanges {
  const [modifiedCells, setModifiedCells] = useState<Map<string, ModifiedCell>>(() => new Map());
  const [deletedRows, setDeletedRows] = useState<Set<number>>(() => new Set());
  const [insertedRows, setInsertedRows] = useState<InsertedRow[]>([]);
  const resetKeyRef = useRef(resetKey);

  useEffect(() => {
    if (resetKeyRef.current !== resetKey) {
      resetKeyRef.current = resetKey;
      setModifiedCells(new Map());
      setDeletedRows(new Set());
      setInsertedRows([]);
    }
  }, [resetKey]);

  const cellKey = (rowIndex: number, colName: string) => `${rowIndex}:${colName}`;

  const modifyCell = useCallback((rowIndex: number, colName: string, newValue: string | null, originalValue: unknown) => {
    setModifiedCells(prev => {
      const next = new Map(prev);
      const key = cellKey(rowIndex, colName);
      // Check if new value matches original — if so, remove the modification
      const origStr = originalValue === null || originalValue === undefined
        ? null
        : String(typeof originalValue === 'object' ? JSON.stringify(originalValue) : originalValue);
      if (newValue === origStr) {
        next.delete(key);
      } else {
        next.set(key, { value: newValue, originalValue });
      }
      return next;
    });
  }, []);

  const revertCell = useCallback((rowIndex: number, colName: string) => {
    setModifiedCells(prev => {
      const next = new Map(prev);
      next.delete(cellKey(rowIndex, colName));
      return next;
    });
  }, []);

  const markRowsDeleted = useCallback((indices: number[]) => {
    setDeletedRows(prev => {
      const next = new Set(prev);
      for (const i of indices) next.add(i);
      return next;
    });
  }, []);

  const unmarkRowDeleted = useCallback((index: number) => {
    setDeletedRows(prev => {
      const next = new Set(prev);
      next.delete(index);
      return next;
    });
  }, []);

  const addInsertedRow = useCallback((columns: string[], autoGeneratedCols: Set<string>) => {
    const tempId = `tmp_${++nextTempId}`;
    const fields: Record<string, string | null> = {};
    const autoFields = new Set<string>();
    for (const col of columns) {
      if (autoGeneratedCols.has(col)) {
        autoFields.add(col);
      } else {
        fields[col] = '';
      }
    }
    setInsertedRows(prev => [...prev, { tempId, fields, autoFields }]);
  }, []);

  const removeInsertedRow = useCallback((tempId: string) => {
    setInsertedRows(prev => prev.filter(r => r.tempId !== tempId));
  }, []);

  const updateInsertedRowField = useCallback((tempId: string, col: string, value: string | null) => {
    setInsertedRows(prev =>
      prev.map(r => r.tempId === tempId ? { ...r, fields: { ...r.fields, [col]: value } } : r)
    );
  }, []);

  const toggleInsertedRowAuto = useCallback((tempId: string, col: string) => {
    setInsertedRows(prev =>
      prev.map(r => {
        if (r.tempId !== tempId) return r;
        const autoFields = new Set(r.autoFields);
        const fields = { ...r.fields };
        if (autoFields.has(col)) {
          autoFields.delete(col);
          fields[col] = '';
        } else {
          autoFields.add(col);
          delete fields[col];
        }
        return { ...r, fields, autoFields };
      })
    );
  }, []);

  const revertAll = useCallback(() => {
    setModifiedCells(new Map());
    setDeletedRows(new Set());
    setInsertedRows([]);
  }, []);

  const clearAfterSubmit = useCallback(() => {
    setModifiedCells(new Map());
    setDeletedRows(new Set());
    setInsertedRows([]);
  }, []);

  const isCellModified = useCallback((rowIndex: number, colName: string) => {
    return modifiedCells.has(cellKey(rowIndex, colName));
  }, [modifiedCells]);

  const isRowDeleted = useCallback((rowIndex: number) => {
    return deletedRows.has(rowIndex);
  }, [deletedRows]);

  const getCellValue = useCallback((rowIndex: number, colName: string): string | null | undefined => {
    const entry = modifiedCells.get(cellKey(rowIndex, colName));
    return entry?.value;
  }, [modifiedCells]);

  // Count: modified cells (excluding cells in deleted rows) + deleted rows + inserted rows
  const modifiedCellRows = new Set<number>();
  for (const key of modifiedCells.keys()) {
    const ri = parseInt(key.split(':')[0]);
    if (!deletedRows.has(ri)) modifiedCellRows.add(ri);
  }
  const changeCount = modifiedCellRows.size + deletedRows.size + insertedRows.length;
  const hasChanges = changeCount > 0;

  return {
    modifiedCells,
    deletedRows,
    insertedRows,
    modifyCell,
    revertCell,
    markRowsDeleted,
    unmarkRowDeleted,
    addInsertedRow,
    removeInsertedRow,
    updateInsertedRowField,
    toggleInsertedRowAuto,
    revertAll,
    clearAfterSubmit,
    changeCount,
    hasChanges,
    isCellModified,
    isRowDeleted,
    getCellValue,
  };
}
