import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import CellContent from './CellContent';
import type { ColumnKeyInfo, ColumnTypeCategory } from '@/types';

const mockSettings = { dateFormat: 'iso' as 'iso' | 'locale' | 'relative' };

vi.mock('@/hooks/useSettings', () => ({
  useSettings: () => ({ settings: mockSettings }),
}));

const renderCellContent = vi.fn((text: string) => text);

function mkProps(overrides: Partial<Parameters<typeof CellContent>[0]> = {}) {
  return {
    cell: 'value',
    colName: 'col',
    colWidth: undefined,
    rowIdx: 0,
    colIdx: 0,
    fkInfo: undefined,
    colType: 'text' as ColumnTypeCategory,
    searchQuery: '',
    renderCellContent,
    onNavigateFk: undefined,
    ...overrides,
  };
}

function renderCell(props: Parameters<typeof CellContent>[0]) {
  return render(
    <table><tbody><tr><CellContent {...props} /></tr></tbody></table>,
  );
}

beforeEach(() => {
  vi.clearAllMocks();
  mockSettings.dateFormat = 'iso';
  renderCellContent.mockImplementation((text: string) => text);
});

describe('CellContent', () => {
  describe('null / undefined cell', () => {
    it('renders italic "null" for null cell', () => {
      renderCell(mkProps({ cell: null }));
      const el = screen.getByText('null');
      expect(el.tagName).toBe('SPAN');
      expect(el.className).toContain('italic');
    });

    it('renders italic "null" for undefined cell', () => {
      renderCell(mkProps({ cell: undefined }));
      expect(screen.getByText('null')).toBeInTheDocument();
    });
  });

  describe('normal (non-FK) cell', () => {
    it('calls renderCellContent with stringified value', () => {
      renderCell(mkProps({ cell: 42 }));
      expect(renderCellContent).toHaveBeenCalledWith('42', 0, 0);
    });

    it('stringifies objects as JSON', () => {
      renderCell(mkProps({ cell: { a: 1 } }));
      expect(renderCellContent).toHaveBeenCalledWith('{"a":1}', 0, 0);
    });

    it('passes rowIdx and colIdx to renderCellContent', () => {
      renderCell(mkProps({ cell: 'x', rowIdx: 3, colIdx: 5 }));
      expect(renderCellContent).toHaveBeenCalledWith('x', 3, 5);
    });
  });

  describe('colWidth style', () => {
    it('applies fixed-width styles when colWidth is provided', () => {
      const { container } = renderCell(mkProps({ colWidth: 120 }));
      const td = container.querySelector('td');
      expect(td?.style.width).toBe('120px');
      expect(td?.style.minWidth).toBe('120px');
      expect(td?.style.maxWidth).toBe('120px');
    });

    it('does not apply width styles when colWidth is undefined', () => {
      const { container } = renderCell(mkProps({ colWidth: undefined }));
      const td = container.querySelector('td');
      expect(td?.style.width).toBe('');
    });
  });

  describe('FK cell', () => {
    const fkInfo: ColumnKeyInfo = {
      columnName: 'user_id',
      isPrimary: false,
      fkRefTable: 'users',
      fkRefColumn: 'id',
      isNullable: false,
      isAutoGenerated: false,
    };
    const onNavigateFk = vi.fn();

    it('shows navigate button with correct title', () => {
      renderCell(mkProps({ cell: '5', fkInfo, onNavigateFk }));
      const btn = screen.getByTitle('Navigate to users.id');
      expect(btn).toBeInTheDocument();
    });

    it('calls onNavigateFk with correct args on button click', () => {
      renderCell(mkProps({ cell: '5', fkInfo, onNavigateFk, colType: 'number' }));
      const btn = screen.getByTitle('Navigate to users.id');
      fireEvent.click(btn);
      expect(onNavigateFk).toHaveBeenCalledWith('users', 'id', '5', 'number');
    });

    it('does not render FK button when onNavigateFk is undefined', () => {
      renderCell(mkProps({ cell: '5', fkInfo, onNavigateFk: undefined }));
      expect(screen.queryByTitle('Navigate to users.id')).not.toBeInTheDocument();
    });

    it('does not render FK button when cell is null', () => {
      renderCell(mkProps({ cell: null, fkInfo, onNavigateFk }));
      expect(screen.queryByTitle('Navigate to users.id')).not.toBeInTheDocument();
    });

    it('does not render FK button when fkRefTable is null', () => {
      const noRefFk: ColumnKeyInfo = { ...fkInfo, fkRefTable: null };
      renderCell(mkProps({ cell: '5', fkInfo: noRefFk, onNavigateFk }));
      expect(screen.queryByTitle(/Navigate to/)).not.toBeInTheDocument();
    });

    it('uses rawStr (not formatted date) for FK value', () => {
      renderCell(mkProps({ cell: '2024-01-15', fkInfo, onNavigateFk, colType: 'date' }));
      fireEvent.click(screen.getByTitle('Navigate to users.id'));
      expect(onNavigateFk).toHaveBeenCalledWith('users', 'id', '2024-01-15', 'date');
    });
  });

  describe('date formatting (iso mode — default mock)', () => {
    it('passes raw value unchanged in iso mode for datetime', () => {
      renderCell(mkProps({ cell: '2024-01-15 10:30:00', colType: 'datetime' }));
      expect(renderCellContent).toHaveBeenCalledWith('2024-01-15 10:30:00', 0, 0);
    });

    it('passes raw value unchanged in iso mode for date', () => {
      renderCell(mkProps({ cell: '2024-01-15', colType: 'date' }));
      expect(renderCellContent).toHaveBeenCalledWith('2024-01-15', 0, 0);
    });

    it('passes raw value unchanged in iso mode for time', () => {
      renderCell(mkProps({ cell: '10:30:00', colType: 'time' }));
      expect(renderCellContent).toHaveBeenCalledWith('10:30:00', 0, 0);
    });

    it('passes raw value for non-date type', () => {
      renderCell(mkProps({ cell: 'hello', colType: 'text' }));
      expect(renderCellContent).toHaveBeenCalledWith('hello', 0, 0);
    });
  });
});

describe('CellContent with locale dateFormat', () => {
  beforeEach(() => {
    mockSettings.dateFormat = 'locale';
  });

  it('formats date colType with toLocaleDateString', () => {
    renderCell(mkProps({ cell: '2024-06-01', colType: 'date' }));
    const called = renderCellContent.mock.calls[0][0];
    expect(typeof called).toBe('string');
    expect(called).not.toBe('');
  });

  it('returns raw value for time colType in locale mode (invalid date string)', () => {
    renderCell(mkProps({ cell: '10:30:00', colType: 'time' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('10:30:00');
  });

  it('returns raw value for time colType in locale mode (valid parseable datetime)', () => {
    renderCell(mkProps({ cell: '2024-01-15T10:30:00', colType: 'time' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('2024-01-15T10:30:00');
  });

  it('formats datetime with toLocaleString in locale mode', () => {
    renderCell(mkProps({ cell: '2024-06-01T10:30:00', colType: 'datetime' }));
    const called = renderCellContent.mock.calls[0][0];
    expect(typeof called).toBe('string');
    expect(called).not.toBe('');
  });

  it('normalizes space-separated datetime to T-separator before parsing', () => {
    renderCell(mkProps({ cell: '2024-06-01 10:30:00', colType: 'datetime' }));
    const called = renderCellContent.mock.calls[0][0];
    expect(called).not.toBe('2024-06-01 10:30:00');
  });

  it('returns raw value for invalid date in locale mode', () => {
    renderCell(mkProps({ cell: 'not-a-date', colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('not-a-date');
  });
});

describe('CellContent with relative dateFormat', () => {
  beforeEach(() => {
    mockSettings.dateFormat = 'relative';
  });

  it('returns raw value for time colType in relative mode (invalid date string)', () => {
    renderCell(mkProps({ cell: '10:30:00', colType: 'time' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('10:30:00');
  });

  it('returns raw value for time colType in relative mode (valid parseable datetime)', () => {
    renderCell(mkProps({ cell: '2024-01-15T10:30:00', colType: 'time' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('2024-01-15T10:30:00');
  });

  it('returns "just now" for a date very close to now', () => {
    renderCell(mkProps({ cell: new Date().toISOString(), colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('just now');
  });

  it('returns minute-relative string for a date ~10 minutes ago', () => {
    const tenMinutesAgo = new Date(Date.now() - 10 * 60 * 1000).toISOString();
    renderCell(mkProps({ cell: tenMinutesAgo, colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toContain('minute');
  });

  it('returns hour-relative string for a date ~2 hours ago', () => {
    const twoHoursAgo = new Date(Date.now() - 2 * 3600 * 1000).toISOString();
    renderCell(mkProps({ cell: twoHoursAgo, colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toContain('hour');
  });

  it('returns day-relative string for a date ~3 days ago', () => {
    const threeDaysAgo = new Date(Date.now() - 3 * 86400 * 1000).toISOString();
    renderCell(mkProps({ cell: threeDaysAgo, colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toContain('day');
  });

  it('returns month-relative string for a date ~2 months ago', () => {
    const twoMonthsAgo = new Date(Date.now() - 60 * 86400 * 1000).toISOString();
    renderCell(mkProps({ cell: twoMonthsAgo, colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toContain('month');
  });

  it('returns year-relative string for a date ~2 years ago', () => {
    const twoYearsAgo = new Date(Date.now() - 2 * 365 * 86400 * 1000).toISOString();
    renderCell(mkProps({ cell: twoYearsAgo, colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toContain('year');
  });

  it('returns future minute-relative string for a date in the future', () => {
    const inTenMinutes = new Date(Date.now() + 10 * 60 * 1000).toISOString();
    renderCell(mkProps({ cell: inTenMinutes, colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toContain('minute');
  });

  it('returns raw value for invalid date in relative mode', () => {
    renderCell(mkProps({ cell: 'not-a-date', colType: 'datetime' }));
    expect(renderCellContent.mock.calls[0][0]).toBe('not-a-date');
  });
});
