import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi, beforeAll } from 'vitest';
import { createRef } from 'react';
import ColumnHeader from './ColumnHeader';
import type { FilterDraft } from '@/hooks/useTableFilters';
import type { ColumnKeyInfo, SortEntry } from '@/types';

// Radix ContextMenu calls scrollIntoView
beforeAll(() => {
  Element.prototype.scrollIntoView = vi.fn();
});

const defaultDraft: FilterDraft = {
  value: '',
  value2: '',
  operator: 'eq',
  caseSensitive: false,
  nullFilter: '',
};

function renderHeader(overrides: Partial<Parameters<typeof ColumnHeader>[0]> = {}) {
  const handlers = {
    onSort: vi.fn(),
    onOpenFilter: vi.fn(),
    onFilterChange: vi.fn(),
    onApplyFilter: vi.fn(),
    onClearFilter: vi.fn(),
    onCloseFilter: vi.fn(),
    onStartResize: vi.fn(),
  };
  const props = {
    col: 'name',
    colType: 'text' as const,
    hasCase: false,
    colWidths: {} as Record<string, number>,
    rawType: 'varchar',
    keyInfo: undefined as ColumnKeyInfo | undefined,
    sortEntry: null as SortEntry | null,
    sortPriority: null as number | null,
    filtered: false,
    openFilterCol: null as string | null,
    filterDraft: defaultDraft,
    filterModalRef: createRef<HTMLDivElement | null>(),
    ...handlers,
    ...overrides,
  };
  const utils = render(
    <table>
      <thead>
        <tr>
          <ColumnHeader {...props} />
        </tr>
      </thead>
    </table>,
  );
  return { ...utils, ...handlers };
}

describe('ColumnHeader — rendering', () => {
  it('displays the column name', () => {
    renderHeader();
    expect(screen.getByText('name')).toBeInTheDocument();
  });

  it('displays rawType subtitle when rawType is non-empty', () => {
    renderHeader({ rawType: 'varchar' });
    expect(screen.getByText('varchar')).toBeInTheDocument();
  });

  it('omits rawType subtitle when rawType is empty string', () => {
    const { container } = renderHeader({ rawType: '' });
    const spans = container.querySelectorAll('span.text-\\[10px\\]');
    expect(spans).toHaveLength(0);
  });

  it('shows Key icon for primary key column', () => {
    const keyInfo: ColumnKeyInfo = {
      columnName: 'name',
      isPrimary: true,
      fkRefTable: null,
      fkRefColumn: null,
      isNullable: false,
      isAutoGenerated: false,
    };
    const { container } = renderHeader({ keyInfo });
    // Key icon renders as an SVG inside the span; lucide adds data-testid or we check SVG presence
    const th = container.querySelector('th')!;
    // The Key icon SVG should be present (amber-500 class)
    expect(th.querySelector('svg.text-amber-500')).toBeInTheDocument();
  });

  it('shows Link icon for foreign key column', () => {
    const keyInfo: ColumnKeyInfo = {
      columnName: 'name',
      isPrimary: false,
      fkRefTable: 'users',
      fkRefColumn: 'id',
      isNullable: true,
      isAutoGenerated: false,
    };
    const { container } = renderHeader({ keyInfo });
    const th = container.querySelector('th')!;
    expect(th.querySelector('svg.text-blue-500')).toBeInTheDocument();
  });

  it('shows both Key and Link icons when column is PK and FK', () => {
    const keyInfo: ColumnKeyInfo = {
      columnName: 'name',
      isPrimary: true,
      fkRefTable: 'users',
      fkRefColumn: 'id',
      isNullable: false,
      isAutoGenerated: false,
    };
    const { container } = renderHeader({ keyInfo });
    const th = container.querySelector('th')!;
    expect(th.querySelector('svg.text-amber-500')).toBeInTheDocument();
    expect(th.querySelector('svg.text-blue-500')).toBeInTheDocument();
  });

  it('sets title to "Primary key" for PK-only column', () => {
    const keyInfo: ColumnKeyInfo = {
      columnName: 'name',
      isPrimary: true,
      fkRefTable: null,
      fkRefColumn: null,
      isNullable: false,
      isAutoGenerated: false,
    };
    const { container } = renderHeader({ keyInfo });
    expect(container.querySelector('th')).toHaveAttribute('title', 'Primary key');
  });

  it('sets title for FK-only column', () => {
    const keyInfo: ColumnKeyInfo = {
      columnName: 'name',
      isPrimary: false,
      fkRefTable: 'orders',
      fkRefColumn: 'user_id',
      isNullable: true,
      isAutoGenerated: false,
    };
    const { container } = renderHeader({ keyInfo });
    expect(container.querySelector('th')).toHaveAttribute(
      'title',
      'Foreign key → orders.user_id',
    );
  });

  it('sets combined title for PK+FK column', () => {
    const keyInfo: ColumnKeyInfo = {
      columnName: 'name',
      isPrimary: true,
      fkRefTable: 'orders',
      fkRefColumn: 'user_id',
      isNullable: false,
      isAutoGenerated: false,
    };
    const { container } = renderHeader({ keyInfo });
    expect(container.querySelector('th')).toHaveAttribute(
      'title',
      'Primary key\nForeign key → orders.user_id',
    );
  });

  it('has no title when column has no key info', () => {
    const { container } = renderHeader({ keyInfo: undefined });
    expect(container.querySelector('th')).not.toHaveAttribute('title');
  });

  it('applies colWidths style when width is defined', () => {
    const { container } = renderHeader({ colWidths: { name: 120 } });
    const th = container.querySelector('th')!;
    expect(th).toHaveStyle({ width: '120px', minWidth: '120px', maxWidth: '120px' });
  });

  it('applies no inline style when col is absent from colWidths', () => {
    const { container } = renderHeader({ colWidths: {} });
    const th = container.querySelector('th')!;
    expect(th.style.width).toBe('');
  });
});

describe('ColumnHeader — sort button', () => {
  it('shows ArrowUpDown (unsorted) when sortEntry is null', () => {
    renderHeader({ sortEntry: null });
    const sortBtn = screen.getByTitle('Sort column');
    // ArrowUpDown has opacity-20 class; ArrowUp/Down use text-blue-500
    expect(sortBtn.querySelector('svg.opacity-20')).toBeInTheDocument();
  });

  it('shows ArrowUp for ascending sort', () => {
    const { container } = renderHeader({ sortEntry: { col: 'name', dir: 'asc' } });
    const sortBtn = screen.getByTitle('Sort column');
    // ArrowUp is blue; no opacity-20
    expect(sortBtn.querySelector('svg.opacity-20')).not.toBeInTheDocument();
    // there should be a blue SVG in the sort button
    expect(container.querySelector('th button[title="Sort column"] svg.text-blue-500')).toBeInTheDocument();
  });

  it('shows ArrowDown for descending sort', () => {
    const { container } = renderHeader({ sortEntry: { col: 'name', dir: 'desc' } });
    const sortBtn = screen.getByTitle('Sort column');
    expect(sortBtn.querySelector('svg.opacity-20')).not.toBeInTheDocument();
    expect(container.querySelector('th button[title="Sort column"] svg.text-blue-500')).toBeInTheDocument();
  });

  it('displays sort priority number when sortPriority is set', () => {
    renderHeader({ sortEntry: { col: 'name', dir: 'asc' }, sortPriority: 2 });
    expect(screen.getByText('2')).toBeInTheDocument();
  });

  it('omits sort priority when sortPriority is null', () => {
    renderHeader({ sortEntry: { col: 'name', dir: 'asc' }, sortPriority: null });
    // should not find a standalone digit from priority
    expect(screen.queryByText('1')).not.toBeInTheDocument();
    expect(screen.queryByText('2')).not.toBeInTheDocument();
  });

  it('calls onSort with col when sort button is clicked', () => {
    const { onSort } = renderHeader();
    fireEvent.click(screen.getByTitle('Sort column'));
    expect(onSort).toHaveBeenCalledWith('name');
  });
});

describe('ColumnHeader — filter button', () => {
  it('has active styling when filtered is true', () => {
    renderHeader({ filtered: true });
    const filterBtn = screen.getByTitle('Filter column');
    expect(filterBtn.className).toMatch(/opacity-100/);
    expect(filterBtn.className).toMatch(/text-blue-500/);
  });

  it('has inactive styling when filtered is false', () => {
    renderHeader({ filtered: false });
    const filterBtn = screen.getByTitle('Filter column');
    expect(filterBtn.className).toMatch(/opacity-20/);
    expect(filterBtn.className).not.toMatch(/text-blue-500/);
  });

  it('calls onOpenFilter with col when filter button is clicked', () => {
    const { onOpenFilter } = renderHeader();
    fireEvent.click(screen.getByTitle('Filter column'));
    expect(onOpenFilter).toHaveBeenCalledWith('name');
  });
});

describe('ColumnHeader — FilterModal', () => {
  it('does not render FilterModal when openFilterCol does not match col', () => {
    renderHeader({ openFilterCol: 'other_col' });
    expect(screen.queryByText('Apply')).not.toBeInTheDocument();
  });

  it('renders FilterModal when openFilterCol matches col', () => {
    renderHeader({ openFilterCol: 'name' });
    expect(screen.getByText('Apply')).toBeInTheDocument();
  });

  it('passes onCloseFilter as onClose to FilterModal', () => {
    const { onCloseFilter } = renderHeader({ openFilterCol: 'name' });
    // Escape in the filter input closes the modal
    fireEvent.keyDown(screen.getByPlaceholderText('Filter…'), { key: 'Escape' });
    expect(onCloseFilter).toHaveBeenCalled();
  });

  it('passes onApplyFilter as onApply to FilterModal', () => {
    const { onApplyFilter } = renderHeader({
      openFilterCol: 'name',
      filterDraft: { ...defaultDraft, value: 'hello' },
    });
    fireEvent.click(screen.getByText('Apply'));
    expect(onApplyFilter).toHaveBeenCalledWith('name', 'text');
  });

  it('passes onClearFilter as onClear to FilterModal', () => {
    const { onClearFilter } = renderHeader({ openFilterCol: 'name' });
    fireEvent.click(screen.getByText('Clear'));
    expect(onClearFilter).toHaveBeenCalledWith('name');
  });

  it('passes onFilterChange as onChange to FilterModal', () => {
    const { onFilterChange } = renderHeader({ openFilterCol: 'name' });
    fireEvent.change(screen.getByPlaceholderText('Filter…'), { target: { value: 'abc' } });
    expect(onFilterChange).toHaveBeenCalledWith(expect.objectContaining({ value: 'abc' }));
  });
});

describe('ColumnHeader — resize handle', () => {
  it('calls onStartResize with event and col on mouseDown', () => {
    const { container, onStartResize } = renderHeader();
    const handle = container.querySelector('div.cursor-col-resize')!;
    fireEvent.mouseDown(handle);
    expect(onStartResize).toHaveBeenCalledWith(expect.any(Object), 'name');
  });
});

describe('ColumnHeader — context menu', () => {
  it('does not render context menu content when onDropColumn is not provided', () => {
    renderHeader({ onDropColumn: undefined });
    // Right-click the th — no menu should appear
    const { container } = renderHeader({ onDropColumn: undefined });
    fireEvent.contextMenu(container.querySelector('th')!);
    expect(screen.queryByText('Drop Column')).not.toBeInTheDocument();
  });

  it('opens context menu on right-click when onDropColumn is provided', () => {
    const onDropColumn = vi.fn();
    const { container } = renderHeader({ onDropColumn });
    fireEvent.contextMenu(container.querySelector('th')!);
    expect(screen.getByText('Drop Column')).toBeInTheDocument();
  });

  it('context menu Sort item calls onSort', () => {
    const onDropColumn = vi.fn();
    const { container, onSort } = renderHeader({ onDropColumn });
    fireEvent.contextMenu(container.querySelector('th')!);
    // Items render in Portal (document.body)
    const sortItem = Array.from(document.body.querySelectorAll('[role="menuitem"]')).find(
      (el) => el.textContent === 'Sort',
    )!;
    fireEvent.click(sortItem);
    expect(onSort).toHaveBeenCalledWith('name');
  });

  it('context menu Filter item calls onOpenFilter', () => {
    const onDropColumn = vi.fn();
    const { container, onOpenFilter } = renderHeader({ onDropColumn });
    fireEvent.contextMenu(container.querySelector('th')!);
    const filterItem = Array.from(document.body.querySelectorAll('[role="menuitem"]')).find(
      (el) => el.textContent === 'Filter',
    )!;
    fireEvent.click(filterItem);
    expect(onOpenFilter).toHaveBeenCalledWith('name');
  });

  it('context menu Drop Column item calls onDropColumn', () => {
    const onDropColumn = vi.fn();
    const { container } = renderHeader({ onDropColumn });
    fireEvent.contextMenu(container.querySelector('th')!);
    const dropItem = Array.from(document.body.querySelectorAll('[role="menuitem"]')).find(
      (el) => el.textContent === 'Drop Column',
    )!;
    fireEvent.click(dropItem);
    expect(onDropColumn).toHaveBeenCalledWith('name');
  });
});
