import { render, screen, waitFor, act, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { invoke } from '@tauri-apps/api/core';
import ELK from 'elkjs/lib/elk.bundled.js';

vi.mock('elkjs/lib/elk.bundled.js', () => ({
  default: class MockELK {
    async layout(graph: { children?: { id: string }[]; edges?: unknown[] }) {
      return {
        ...graph,
        children: (graph.children ?? []).map((c) => ({ ...c, x: 100, y: 200 })),
      };
    }
  },
}));

vi.mock('@/lib/auto-reconnect', () => ({
  withAutoReconnect: (_conn: string, _db: string, fn: () => Promise<unknown>) => fn(),
}));

vi.mock('@xyflow/react', async () => {
  const React = await import('react');

  function useNodesState(initial: unknown[]) {
    const [nodes, setNodes] = React.useState<unknown[]>(initial);
    return [nodes, setNodes, vi.fn()] as const;
  }

  function useEdgesState(initial: unknown[]) {
    const [edges, setEdges] = React.useState<unknown[]>(initial);
    return [edges, setEdges, vi.fn()] as const;
  }

  function ReactFlow({ nodes, nodeTypes, onNodeDragStop, children }: {
    nodes: Array<{ id: string; type?: string; data: unknown }>;
    nodeTypes?: Record<string, React.ComponentType<{ id: string; data: unknown }>>;
    onNodeDragStop?: () => void;
    children?: React.ReactNode;
  }) {
    return React.createElement(
      'div',
      { 'data-testid': 'react-flow' },
      React.createElement('button', { onClick: () => onNodeDragStop?.() }, 'trigger-drag-stop'),
      ...(nodes ?? []).map((node) => {
        const NodeComp = nodeTypes?.[node.type ?? ''];
        return NodeComp
          ? React.createElement(NodeComp, { key: node.id, id: node.id, data: node.data as never })
          : null;
      }),
      children,
    );
  }

  return {
    ReactFlow,
    Background: () => null,
    Controls: () => null,
    MiniMap: () => null,
    Handle: () => null,
    Position: { Left: 'left', Right: 'right' },
    MarkerType: { ArrowClosed: 'arrowclosed' },
    useNodesState,
    useEdgesState,
  };
});

import SchemaTab from './SchemaTab';

const singleTableSchema = [
  {
    tableName: 'users',
    columns: [
      { name: 'id', dataType: 'integer' },
      { name: 'name', dataType: 'varchar' },
      { name: 'org_id', dataType: 'integer' },
    ],
    keys: [
      { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: true },
      { columnName: 'org_id', isPrimary: false, fkRefTable: 'orgs', fkRefColumn: 'id', isNullable: true, isAutoGenerated: false },
    ],
  },
];

const multiTableSchema = [
  ...singleTableSchema,
  {
    tableName: 'orgs',
    columns: [
      { name: 'id', dataType: 'integer' },
      { name: 'name', dataType: 'varchar' },
    ],
    keys: [
      { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: true },
    ],
  },
];

function defaultProps(overrides: Partial<{ connectionName: string; database: string; refreshKey: number }> = {}) {
  return { connectionName: 'myconn', database: 'mydb', ...overrides };
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe('SchemaTab', () => {
  describe('loading state', () => {
    it('shows "Loading schema…" initially', () => {
      vi.mocked(invoke).mockReturnValue(new Promise(() => {}));
      render(<SchemaTab {...defaultProps()} />);
      expect(screen.getByText('Loading schema…')).toBeInTheDocument();
    });

    it('shows toolbar with connection and database in header', () => {
      vi.mocked(invoke).mockReturnValue(new Promise(() => {}));
      render(<SchemaTab {...defaultProps()} />);
      expect(screen.getByText('myconn / mydb · Schema')).toBeInTheDocument();
    });

    it('does not show table count while loading', () => {
      vi.mocked(invoke).mockReturnValue(new Promise(() => {}));
      render(<SchemaTab {...defaultProps()} />);
      expect(screen.queryByText(/\d+ table/)).not.toBeInTheDocument();
    });
  });

  describe('error state', () => {
    it('shows error message when get_schema fails', async () => {
      vi.mocked(invoke).mockRejectedValue('Connection refused');
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('Connection refused')).toBeInTheDocument();
      });
    });

    it('does not show table count on error', async () => {
      vi.mocked(invoke).mockRejectedValue('Some error');
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.queryByText(/\d+ table/)).not.toBeInTheDocument();
      });
    });
  });

  describe('empty state', () => {
    it('shows "No tables found" when schema returns empty array', async () => {
      vi.mocked(invoke).mockResolvedValue([]);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('No tables found')).toBeInTheDocument();
      });
    });
  });

  describe('successful load', () => {
    it('renders ReactFlow when tables exist', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByTestId('react-flow')).toBeInTheDocument();
      });
    });

    it('shows singular "table" for exactly 1 table', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('1 table')).toBeInTheDocument();
      });
    });

    it('shows plural "tables" for multiple tables', async () => {
      vi.mocked(invoke).mockResolvedValue(multiTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('2 tables')).toBeInTheDocument();
      });
    });
  });

  describe('TableNode rendering', () => {
    it('renders table name in node header', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('users')).toBeInTheDocument();
      });
    });

    it('renders column names and data types', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('name')).toBeInTheDocument();
        expect(screen.getAllByText('integer').length).toBeGreaterThan(0);
        expect(screen.getByText('varchar')).toBeInTheDocument();
      });
    });

    it('renders Key icon (svg) for primary key column', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      const { container } = render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        // lucide-react Key and Link icons render as SVGs
        expect(container.querySelectorAll('svg').length).toBeGreaterThan(0);
      });
    });

    it('renders a plain spacer span for a non-pk non-fk column', async () => {
      // The 'name' column is neither PK nor FK → renders <span className="w-2.5 ...">
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      const { container } = render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('users')).toBeInTheDocument();
      });
      // At least one spacer span with w-2.5 class (from non-pk/non-fk column)
      expect(container.querySelector('.w-2\\.5')).toBeInTheDocument();
    });
  });

  describe('localStorage persistence', () => {
    it('saves node positions to localStorage after drag stop', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByTestId('react-flow')).toBeInTheDocument();
      });

      fireEvent.click(screen.getByText('trigger-drag-stop'));

      const key = 'schema-layout::myconn::mydb';
      const saved = localStorage.getItem(key);
      expect(saved).not.toBeNull();
      const parsed = JSON.parse(saved!);
      expect(parsed).toHaveProperty('users');
    });

    it('uses saved positions (allSaved=true) when all tables have positions', async () => {
      const key = 'schema-layout::myconn::mydb';
      localStorage.setItem(key, JSON.stringify({ users: { x: 50, y: 50 } }));

      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('1 table')).toBeInTheDocument();
      });
    });

    it('falls back to ELK when saved positions are incomplete (allSaved=false)', async () => {
      const key = 'schema-layout::myconn::mydb';
      // Only 'users' saved, 'orgs' is missing → allSaved=false → uses ELK
      localStorage.setItem(key, JSON.stringify({ users: { x: 50, y: 50 } }));

      vi.mocked(invoke).mockResolvedValue(multiTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('2 tables')).toBeInTheDocument();
      });
    });

    it('handles corrupted localStorage data gracefully (returns null positions → ELK path)', async () => {
      const key = 'schema-layout::myconn::mydb';
      localStorage.setItem(key, 'invalid{{{json');

      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByTestId('react-flow')).toBeInTheDocument();
      });
    });
  });

  describe('refreshKey', () => {
    it('re-fetches schema when refreshKey changes', async () => {
      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      const { rerender } = render(<SchemaTab {...defaultProps({ refreshKey: 0 })} />);
      await waitFor(() => {
        expect(screen.getByText('1 table')).toBeInTheDocument();
      });

      vi.mocked(invoke).mockResolvedValue(multiTableSchema);
      rerender(<SchemaTab {...defaultProps({ refreshKey: 1 })} />);
      await waitFor(() => {
        expect(screen.getByText('2 tables')).toBeInTheDocument();
      });
    });
  });

  describe('FK edges', () => {
    it('renders without error when FK relationship exists between tables', async () => {
      // multiTableSchema: users.org_id → orgs.id
      vi.mocked(invoke).mockResolvedValue(multiTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('2 tables')).toBeInTheDocument();
      });
    });
  });

  describe('cancellation on unmount', () => {
    it('does not update state when component unmounts before fetch resolves', async () => {
      let resolveSchema!: (v: unknown) => void;
      const schemaPromise = new Promise((resolve) => { resolveSchema = resolve; });
      vi.mocked(invoke).mockReturnValue(schemaPromise);

      const { unmount } = render(<SchemaTab {...defaultProps()} />);
      unmount();

      await act(async () => {
        resolveSchema(singleTableSchema);
        await Promise.resolve();
      });
      // No errors or state update warnings = cancellation guard worked
    });

    it('does not update error state when component unmounts before fetch rejects', async () => {
      let rejectSchema!: (err: unknown) => void;
      const schemaPromise = new Promise<never>((_, reject) => { rejectSchema = reject; });
      vi.mocked(invoke).mockReturnValue(schemaPromise);

      const { unmount } = render(<SchemaTab {...defaultProps()} />);
      unmount(); // sets cancelled = true

      await act(async () => {
        rejectSchema('error after unmount');
        await Promise.resolve();
      });
      // No state updates, no warnings = cancelled guard in catch worked
    });
  });

  describe('edge deduplication', () => {
    it('deduplicates FK edges with the same source→target::column', async () => {
      // Two keys with the identical edgeId to exercise the edgeSet.has branch
      const schemaWithDuplicateFK = [
        {
          tableName: 'users',
          columns: [{ name: 'org_id', dataType: 'integer' }],
          keys: [
            { columnName: 'org_id', isPrimary: false, fkRefTable: 'orgs', fkRefColumn: 'id', isNullable: true, isAutoGenerated: false },
            { columnName: 'org_id', isPrimary: false, fkRefTable: 'orgs', fkRefColumn: 'id', isNullable: true, isAutoGenerated: false },
          ],
        },
        {
          tableName: 'orgs',
          columns: [{ name: 'id', dataType: 'integer' }],
          keys: [],
        },
      ];
      vi.mocked(invoke).mockResolvedValue(schemaWithDuplicateFK);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByText('2 tables')).toBeInTheDocument();
      });
    });
  });

  describe('ELK layout fallback positions', () => {
    it('uses (0,0) for nodes not found in ELK output (elkNode undefined → ?? 0 branch)', async () => {
      // Make ELK return empty children so elkNode is undefined for all nodes
      vi.spyOn((ELK as unknown as { prototype: { layout: () => Promise<unknown> } }).prototype, 'layout')
        .mockResolvedValueOnce({ id: 'root', children: [] });

      vi.mocked(invoke).mockResolvedValue(singleTableSchema);
      render(<SchemaTab {...defaultProps()} />);
      await waitFor(() => {
        expect(screen.getByTestId('react-flow')).toBeInTheDocument();
      });
    });
  });
});
