export type DbType = "postgres" | "mysql"
export type SidebarPanel = 'connections' | 'queries' | 'settings'
export type TabType = 'browse' | 'saved-query' | 'create-table' | 'schema-diagram'

export interface SavedConnection {
  name: string
  dbType: DbType
  host: string
  port: number
  database: string
  username: string
  // password is stored in the OS keychain, never sent to the frontend
}

export interface SortEntry {
  col: string
  dir: 'asc' | 'desc'
}

export type ColumnTypeCategory =
  | 'text' | 'number' | 'boolean'
  | 'date' | 'time' | 'datetime'
  | 'json' | 'other'

export type FilterOperator = 'eq' | 'gt' | 'gte' | 'lt' | 'lte' | 'between'

export interface FilterEntry {
  col: string
  value: string
  value2?: string // upper bound for "between" operator
  operator?: FilterOperator // default 'eq'
  caseSensitive: boolean
  colType: ColumnTypeCategory
  exact?: boolean // true = exact equality (used for FK navigation)
  nullFilter?: 'is_null' | 'is_not_null'
}

export interface ColumnInfo {
  name: string
  dataType: string
}

export interface TableSchema {
  tableName: string
  columns: ColumnInfo[]
  keys: ColumnKeyInfo[]
}

export interface ColumnKeyInfo {
  columnName: string
  isPrimary: boolean
  fkRefTable: string | null
  fkRefColumn: string | null
  isNullable: boolean
  isAutoGenerated: boolean
}

export interface QueryResult {
  columns: string[]
  column_types: string[] // ColumnTypeCategory[] — may be empty
  column_raw_types: string[] // raw DB type names, lowercased — may be empty
  rows: unknown[][]
  row_count: number
  sql: string
  execution_time_ms: number
}

export interface SavedQuery {
  id: string
  name: string
  sql: string
  connectionName: string
  database?: string
}

export interface TabEntry {
  id: string
  connectionName: string
  database?: string // populated for browse tabs
  type: TabType
  table?: string // only for browse tabs
  savedQueryId?: string // only for saved-query tabs
  initialFilters?: FilterEntry[]
  filterKey?: number // increment to force DataTable reset with new initialFilters
  refreshKey?: number // increment to force data re-fetch without resetting filters
  preview?: boolean // true = preview tab (italic, replaced on next single-click)
}
