import { render, screen, fireEvent, act } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { invoke } from '@tauri-apps/api/core';
import DataTable from './index';

// Mock hooks with heavy Tauri/storage deps
vi.mock('@/hooks/useTableData');
vi.mock('@/hooks/useTableFilters');
vi.mock('@/hooks/useSettings', () => ({
  useSettings: () => ({ settings: { dateFormat: 'iso', fontSize: 13, tableDensity: 'comfortable', defaultPageSize: 50, defaultConnection: '', aiModel: '' } }),
}));

import { useTableData } from '@/hooks/useTableData';
import { useTableFilters } from '@/hooks/useTableFilters';

const mockedUseTableData = vi.mocked(useTableData);
const mockedUseTableFilters = vi.mocked(useTableFilters);

const defaultResult = {
  columns: ['id', 'name'],
  rows: [[1, 'Alice'], [2, 'Bob']],
  row_count: 2,
  sql: 'SELECT * FROM users',
  column_types: ['number', 'text'],
  column_raw_types: ['int4', 'varchar'],
  execution_time_ms: 5,
};

const defaultTableDataReturn = {
  result: defaultResult,
  error: null,
  loading: false,
  totalCount: null,
  totalCountLoading: false,
  loadTotalCount: vi.fn(),
  columnTypes: { id: 'number' as const, name: 'text' as const },
  columnRawTypes: { id: 'int4', name: 'varchar' },
  columnKeys: {},
};

const defaultFiltersReturn = {
  sortEntries: [],
  filterEntries: [],
  pageSize: 50,
  setPageSize: vi.fn(),
  setSortEntries: vi.fn(),
  setFilterEntries: vi.fn(),
  handleSort: vi.fn(),
  setFilterDraft: vi.fn(),
  applyFilter: vi.fn(),
  clearFilter: vi.fn(),
  openFilterModal: vi.fn(),
  closeFilter: vi.fn(),
  openFilterCol: null,
  filterDraft: { value: '', value2: '', operator: 'eq' as const, caseSensitive: false, nullFilter: '' as const },
  filterModalRef: { current: null },
};

function defaultProps(overrides: Partial<Parameters<typeof DataTable>[0]> = {}) {
  return {
    connectionName: 'myconn',
    database: 'mydb',
    table: 'users',
    dbType: undefined as Parameters<typeof DataTable>[0]['dbType'],
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn });
  mockedUseTableFilters.mockReturnValue({ ...defaultFiltersReturn } as ReturnType<typeof useTableFilters>);
});

describe('DataTable', () => {
  describe('early return states', () => {
    it('shows "Loading…" when loading=true and result=null', () => {
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, loading: true, result: null });
      render(<DataTable {...defaultProps()} />);
      expect(screen.getByText('Loading…')).toBeInTheDocument();
    });

    it('shows error message when error is set and result=null', () => {
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, error: 'DB error', result: null });
      render(<DataTable {...defaultProps()} />);
      expect(screen.getByText('DB error')).toBeInTheDocument();
    });

    it('renders nothing when result=null and no error/loading', () => {
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, result: null });
      const { container } = render(<DataTable {...defaultProps()} />);
      expect(container.firstChild).toBeNull();
    });
  });

  describe('basic render', () => {
    it('renders column headers', () => {
      render(<DataTable {...defaultProps()} />);
      expect(screen.getByText('id')).toBeInTheDocument();
      expect(screen.getByText('name')).toBeInTheDocument();
    });

    it('renders row data', () => {
      render(<DataTable {...defaultProps()} />);
      expect(screen.getByText('Alice')).toBeInTheDocument();
      expect(screen.getByText('Bob')).toBeInTheDocument();
    });

    it('renders row count in toolbar', () => {
      render(<DataTable {...defaultProps()} />);
      expect(screen.getByText(/2 of/)).toBeInTheDocument();
    });

    it('shows "No rows found" when rows is empty', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        result: { ...defaultResult, rows: [], row_count: 0 },
      });
      render(<DataTable {...defaultProps()} />);
      expect(screen.getByText('No rows found')).toBeInTheDocument();
    });
  });

  describe('canEdit mode', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    it('uses CellContent (no edit mode) when no pkColumn or no dbType', () => {
      render(<DataTable {...defaultProps({ dbType: undefined })} />);
      // No tabIndex=0 cells in edit mode; just regular td
      const cells = document.querySelectorAll('td[tabindex]');
      expect(cells).toHaveLength(0);
    });

    it('uses EditableCell when pkColumn exists and dbType set', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      // EditableCell renders TableCell with tabIndex=-1 for non-active cells
      const cells = document.querySelectorAll('td[tabindex="-1"]');
      expect(cells.length).toBeGreaterThan(0);
    });
  });

  describe('row selection', () => {
    it('clicking row index cell selects the row', () => {
      render(<DataTable {...defaultProps()} />);
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      // The row should get data-state="selected"
      expect(screen.getByText('1 selected')).toBeInTheDocument();
    });

    it('clicking selected row deselects it', () => {
      render(<DataTable {...defaultProps()} />);
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      expect(screen.getByText('1 selected')).toBeInTheDocument();
      fireEvent.click(indexCells[0]);
      expect(screen.queryByText(/selected/)).not.toBeInTheDocument();
    });

    it('shift+click selects a range', () => {
      render(<DataTable {...defaultProps()} />);
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(indexCells[1], { shiftKey: true });
      expect(screen.getByText('2 selected')).toBeInTheDocument();
    });
  });

  describe('stage delete', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    it('delete button marks selected rows as deleted', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      // Select a row
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      // Click delete button
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));
      // The row should now show "Click to undelete"
      expect(screen.getByTitle('Click to undelete')).toBeInTheDocument();
    });

    it('clicking index cell on deleted row undeletes it', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      // Select and delete row
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));
      // Now click the undelete cell
      const undeleteCell = screen.getByTitle('Click to undelete');
      fireEvent.click(undeleteCell);
      // Should no longer show undelete
      expect(screen.queryByTitle('Click to undelete')).not.toBeInTheDocument();
    });
  });

  describe('stage insert', () => {
    it('clicking Add row inserts a new row with inputs', () => {
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      // Should show an input for the non-auto fields
      const inputs = screen.getAllByRole('textbox');
      expect(inputs.length).toBeGreaterThan(0);
    });

    it('inserted row has a remove (×) button', () => {
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      expect(screen.getByTitle('Remove new row')).toBeInTheDocument();
    });

    it('clicking remove button removes the inserted row', () => {
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      fireEvent.click(screen.getByTitle('Remove new row'));
      expect(screen.queryByTitle('Remove new row')).not.toBeInTheDocument();
    });
  });

  describe('submit changes', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    it('handleSubmit calls invoke with submit_table_changes and onRefresh', async () => {
      const onRefresh = vi.fn();
      vi.mocked(invoke).mockResolvedValueOnce(undefined);
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres', onRefresh })} />);

      // Select and delete a row to create a change
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      // Click submit
      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      expect(invoke).toHaveBeenCalledWith('submit_table_changes', expect.objectContaining({
        connection: 'myconn',
        database: 'mydb',
        table: 'users',
      }));
      expect(onRefresh).toHaveBeenCalledTimes(1);
    });

    it('handleSubmit shows mutationError on failure', async () => {
      const pkKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      vi.mocked(invoke).mockRejectedValueOnce('DB write failed');
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkKeys,
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      // Select and delete a row to create a change
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      expect(screen.getByText('DB write failed')).toBeInTheDocument();
    });
  });

  describe('discard changes', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    it('handleDiscard reverts all changes', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      // Create a change
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      // Discard
      fireEvent.click(screen.getByTitle('Discard all changes'));
      expect(screen.queryByTitle('Click to undelete')).not.toBeInTheDocument();
    });
  });

  describe('refresh', () => {
    it('handleRefresh with no changes calls onRefresh', () => {
      const onRefresh = vi.fn();
      render(<DataTable {...defaultProps({ onRefresh })} />);
      fireEvent.click(screen.getByTitle('Refresh'));
      expect(onRefresh).toHaveBeenCalledTimes(1);
    });

    it('handleRefresh with changes shows confirm dialog; cancel keeps changes', () => {
      const pkColumnKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      const onRefresh = vi.fn();
      vi.spyOn(window, 'confirm').mockReturnValueOnce(false);
      render(<DataTable {...defaultProps({ dbType: 'postgres', onRefresh })} />);

      // Create a change
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      fireEvent.click(screen.getByTitle('Refresh'));
      expect(window.confirm).toHaveBeenCalledTimes(1);
      expect(onRefresh).not.toHaveBeenCalled();
      // Change still present
      expect(screen.getByTitle('Click to undelete')).toBeInTheDocument();
    });

    it('handleRefresh with changes; confirm=true reverts and refreshes', () => {
      const pkColumnKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: pkColumnKeys,
      });
      const onRefresh = vi.fn();
      vi.spyOn(window, 'confirm').mockReturnValueOnce(true);
      render(<DataTable {...defaultProps({ dbType: 'postgres', onRefresh })} />);

      // Create a change
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      fireEvent.click(screen.getByTitle('Refresh'));
      expect(onRefresh).toHaveBeenCalledTimes(1);
      expect(screen.queryByTitle('Click to undelete')).not.toBeInTheDocument();
    });
  });

  describe('column visibility', () => {
    it('hiding a column removes it from the table headers', () => {
      render(<DataTable {...defaultProps()} />);
      // Verify 'name' column header exists before hiding
      expect(document.querySelector('th .col-name-text, thead th')).toBeTruthy();
      // Open columns popover
      fireEvent.click(screen.getByText('Columns'));
      // Uncheck 'name' column (second checkbox)
      const checkboxes = screen.getAllByRole('checkbox');
      fireEvent.click(checkboxes[1]);
      // 'name' column header (th element) should be gone; the popover span may still exist
      const ths = document.querySelectorAll('thead th');
      const headerTexts = Array.from(ths).map((th) => th.textContent ?? '');
      expect(headerTexts.some((t) => t.includes('name'))).toBe(false);
    });
  });

  describe('search bar', () => {
    it('toggles search bar when search button is clicked', () => {
      render(<DataTable {...defaultProps()} />);
      expect(screen.queryByPlaceholderText('Search in table…')).not.toBeInTheDocument();
      fireEvent.click(screen.getByTitle('Search (⌘F)'));
      expect(screen.getByPlaceholderText('Search in table…')).toBeInTheDocument();
    });
  });

  describe('DropColumnModal', () => {
    it('opens DropColumnModal when a column header triggers drop', () => {
      // DropColumnModal requires dbType to be set; the modal appears when setDropColumnModal is called
      // We trigger this by right-clicking a column header - but ColumnHeader is a child component
      // Just verify the DataTable renders without DropColumnModal by default
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    });
  });

  describe('onOpenSchemaDiagram', () => {
    it('passes onOpenSchemaDiagram to toolbar', () => {
      const onOpenSchemaDiagram = vi.fn();
      render(<DataTable {...defaultProps({ onOpenSchemaDiagram })} />);
      expect(screen.getByTitle('Schema Diagram')).toBeInTheDocument();
      fireEvent.click(screen.getByTitle('Schema Diagram'));
      expect(onOpenSchemaDiagram).toHaveBeenCalledTimes(1);
    });
  });

  describe('inserted row fields', () => {
    it('boolean column in inserted row renders a select', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        result: { ...defaultResult, columns: ['id', 'active'], rows: [[1, true]] },
        columnTypes: { id: 'number' as const, active: 'boolean' as const },
      });
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      const selects = screen.getAllByRole('combobox');
      // At least one select for the boolean column
      expect(selects.length).toBeGreaterThan(0);
    });

    it('changing boolean select updates inserted row field', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        result: { ...defaultResult, columns: ['id', 'active'], rows: [[1, true]] },
        columnTypes: { id: 'number' as const, active: 'boolean' as const },
      });
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      const select = screen.getAllByRole('combobox')[0];
      fireEvent.change(select, { target: { value: '1' } });
      // No error thrown = handler was called
      expect(select).toBeInTheDocument();
    });

    it('changing text input updates inserted row field', () => {
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      const inputs = screen.getAllByRole('textbox');
      fireEvent.change(inputs[0], { target: { value: 'test value' } });
      expect(inputs[0]).toBeInTheDocument();
    });

    it('NULL button appears for nullable non-auto column and toggles null state', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: {
          name: {
            columnName: 'name',
            isPrimary: false,
            fkRefTable: null,
            fkRefColumn: null,
            isNullable: true,
            isAutoGenerated: false,
          },
        },
      });
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Add row'));
      const nullBtns = screen.getAllByText('NULL');
      expect(nullBtns.length).toBeGreaterThan(0);
      fireEvent.click(nullBtns[0]);
      // After clicking, the field should be null; clicking again should un-null it
      expect(screen.getAllByText('NULL').length).toBeGreaterThan(0);
    });

    it('Auto button appears for auto-generated column', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: {
          id: {
            columnName: 'id',
            isPrimary: true,
            fkRefTable: null,
            fkRefColumn: null,
            isNullable: false,
            isAutoGenerated: true,
          },
        },
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      fireEvent.click(screen.getByTitle('Add row'));
      expect(screen.getAllByText('Auto').length).toBeGreaterThan(0);
    });

    it('clicking Auto button toggles auto state', () => {
      mockedUseTableData.mockReturnValue({
        ...defaultTableDataReturn,
        columnKeys: {
          id: {
            columnName: 'id',
            isPrimary: true,
            fkRefTable: null,
            fkRefColumn: null,
            isNullable: false,
            isAutoGenerated: true,
          },
        },
      });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      fireEvent.click(screen.getByTitle('Add row'));
      const autoBtns = screen.getAllByText('Auto');
      fireEvent.click(autoBtns[0]);
      // Auto toggled; field becomes editable
      expect(screen.getAllByText('Auto').length).toBeGreaterThan(0);
    });
  });

  describe('multi-sort priority display', () => {
    it('renders sort priority when multiple sort entries are active', () => {
      mockedUseTableFilters.mockReturnValue({
        ...defaultFiltersReturn,
        sortEntries: [
          { col: 'id', dir: 'asc' as const },
          { col: 'name', dir: 'desc' as const },
        ],
      } as ReturnType<typeof useTableFilters>);
      render(<DataTable {...defaultProps()} />);
      // Both columns are sorted; sortPriority (entryIdx+1) should be computed for both
      // Just verify the component renders without error
      expect(screen.getByText('id')).toBeInTheDocument();
      expect(screen.getByText('name')).toBeInTheDocument();
    });
  });

  describe('DataTable toolbar additional', () => {
    it('"Clear filters" disabled when hasChanges=true', () => {
      const pkColumnKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
      mockedUseTableFilters.mockReturnValue({
        ...defaultFiltersReturn,
        filterEntries: [{ col: 'name', value: 'Alice', caseSensitive: false, colType: 'text' as const }],
      } as ReturnType<typeof useTableFilters>);
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      // Select and delete a row to get hasChanges=true
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      const clearFiltersBtn = screen.getByText('Clear filters').closest('button')!;
      expect(clearFiltersBtn).toBeDisabled();
    });
  });

  describe('search bar close', () => {
    it('closes search bar when search button is clicked a second time', () => {
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByTitle('Search (⌘F)'));
      expect(screen.getByPlaceholderText('Search in table…')).toBeInTheDocument();
      fireEvent.click(screen.getByTitle('Search (⌘F)'));
      expect(screen.queryByPlaceholderText('Search in table…')).not.toBeInTheDocument();
    });
  });

  describe('onPromote callbacks', () => {
    it('calls onPromote when clearing sort', () => {
      const onPromote = vi.fn();
      mockedUseTableFilters.mockReturnValue({
        ...defaultFiltersReturn,
        sortEntries: [{ col: 'id', dir: 'asc' as const }],
      } as ReturnType<typeof useTableFilters>);
      render(<DataTable {...defaultProps({ onPromote })} />);
      fireEvent.click(screen.getByText('Clear sorting'));
      expect(onPromote).toHaveBeenCalledTimes(1);
    });

    it('calls onPromote when clearing filters', () => {
      const onPromote = vi.fn();
      mockedUseTableFilters.mockReturnValue({
        ...defaultFiltersReturn,
        filterEntries: [{ col: 'name', value: 'Alice', caseSensitive: false, colType: 'text' as const }],
      } as ReturnType<typeof useTableFilters>);
      render(<DataTable {...defaultProps({ onPromote })} />);
      fireEvent.click(screen.getByText('Clear filters'));
      expect(onPromote).toHaveBeenCalledTimes(1);
    });
  });

  describe('submit with inserted rows', () => {
    it('calls invoke with inserts array containing row fields', async () => {
      vi.mocked(invoke).mockResolvedValueOnce(undefined);
      render(<DataTable {...defaultProps()} />);

      fireEvent.click(screen.getByTitle('Add row'));
      const inputs = screen.getAllByRole('textbox');
      fireEvent.change(inputs[0], { target: { value: 'Charlie' } });

      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      expect(invoke).toHaveBeenCalledWith(
        'submit_table_changes',
        expect.objectContaining({
          inserts: expect.arrayContaining([expect.any(Array)]),
        })
      );
    });

    it('clears inserted rows after successful submit', async () => {
      vi.mocked(invoke).mockResolvedValueOnce(undefined);
      render(<DataTable {...defaultProps()} />);

      fireEvent.click(screen.getByTitle('Add row'));
      expect(screen.getByTitle('Remove new row')).toBeInTheDocument();

      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      expect(screen.queryByTitle('Remove new row')).not.toBeInTheDocument();
    });
  });

  describe('mutationError lifecycle', () => {
    it('clears mutationError when discard is clicked after a failed submit', async () => {
      const pkColumnKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      vi.mocked(invoke).mockRejectedValueOnce('Write failed');
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      expect(screen.getByText('Write failed')).toBeInTheDocument();

      fireEvent.click(screen.getByTitle('Discard all changes'));
      expect(screen.queryByText('Write failed')).not.toBeInTheDocument();
    });
  });

  describe('pagination disabled state', () => {
    it('"Rows per page" select is disabled when hasChanges=true', () => {
      const pkColumnKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      const rowsPerPageSelect = screen.getByDisplayValue('50');
      expect(rowsPerPageSelect).toBeDisabled();
    });
  });

  describe('multi-row delete', () => {
    it('deleting multiple selected rows shows multiple undelete markers', () => {
      const pkColumnKeys = {
        id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
      };
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(indexCells[1], { shiftKey: true });
      expect(screen.getByText('2 selected')).toBeInTheDocument();

      fireEvent.click(screen.getByTitle('Mark 2 row(s) for deletion'));
      const undeleteTitles = screen.getAllByTitle('Click to undelete');
      expect(undeleteTitles).toHaveLength(2);
    });
  });

  describe('EditableCell click and edit interactions', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    beforeEach(() => {
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
    });

    it('clicking EditableCell activates it (onActivate callback)', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const aliceCell = screen.getByText('Alice').closest('td')!;
      expect(aliceCell).toHaveAttribute('tabIndex', '-1');
      fireEvent.click(aliceCell);
      expect(aliceCell).toHaveAttribute('tabIndex', '0');
    });

    it('double-clicking editable cell starts editing (onStartEdit callback)', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const aliceCell = screen.getByText('Alice').closest('td')!;
      fireEvent.click(aliceCell);
      fireEvent.doubleClick(aliceCell);
      expect(aliceCell.querySelector('input')).toBeInTheDocument();
    });

    it('editing a cell and blurring commits the value (onModify + onStopEdit callbacks)', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const aliceCell = screen.getByText('Alice').closest('td')!;
      fireEvent.click(aliceCell);
      fireEvent.doubleClick(aliceCell);
      const input = aliceCell.querySelector('input')!;
      fireEvent.change(input, { target: { value: 'Alicia' } });
      fireEvent.blur(input);
      expect(screen.getByText('Alicia')).toBeInTheDocument();
      expect(aliceCell.querySelector('input')).not.toBeInTheDocument();
    });
  });

  describe('cell keyboard navigation (handleNavigate)', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    beforeEach(() => {
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
    });

    it('ArrowDown moves active cell to next row', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const aliceCell = screen.getByText('Alice').closest('td')!;
      fireEvent.click(aliceCell);
      expect(aliceCell).toHaveAttribute('tabIndex', '0');
      fireEvent.keyDown(aliceCell, { key: 'ArrowDown' });
      const bobCell = screen.getByText('Bob').closest('td')!;
      expect(bobCell).toHaveAttribute('tabIndex', '0');
    });

    it('ArrowUp moves active cell to previous row', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const bobCell = screen.getByText('Bob').closest('td')!;
      fireEvent.click(bobCell);
      fireEvent.keyDown(bobCell, { key: 'ArrowUp' });
      const aliceCell = screen.getByText('Alice').closest('td')!;
      expect(aliceCell).toHaveAttribute('tabIndex', '0');
    });

    it('ArrowRight moves active cell to next column', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      // First EditableCell td is the id cell of row 0 (pk column)
      const idCell = document.querySelectorAll('td[tabindex="-1"]')[0] as HTMLElement;
      fireEvent.click(idCell);
      expect(idCell).toHaveAttribute('tabIndex', '0');
      fireEvent.keyDown(idCell, { key: 'ArrowRight' });
      const aliceCell = screen.getByText('Alice').closest('td')!;
      expect(aliceCell).toHaveAttribute('tabIndex', '0');
    });

    it('ArrowLeft moves active cell to previous column', () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const aliceCell = screen.getByText('Alice').closest('td')!;
      fireEvent.click(aliceCell);
      fireEvent.keyDown(aliceCell, { key: 'ArrowLeft' });
      const idCell = document.querySelectorAll('td[tabindex="0"]')[0] as HTMLElement;
      // id cell (col 0) should now be active
      expect(idCell).toHaveAttribute('tabIndex', '0');
    });
  });

  describe('submit with cell updates', () => {
    const pkColumnKeys = {
      id: { columnName: 'id', isPrimary: true, fkRefTable: null, fkRefColumn: null, isNullable: false, isAutoGenerated: false },
    };

    it('modifying a cell and submitting calls invoke with updates (covers lines 203-207, 213)', async () => {
      vi.mocked(invoke).mockResolvedValueOnce(undefined);
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      const aliceCell = screen.getByText('Alice').closest('td')!;
      fireEvent.click(aliceCell);
      fireEvent.doubleClick(aliceCell);
      const input = aliceCell.querySelector('input')!;
      fireEvent.change(input, { target: { value: 'Alicia' } });
      fireEvent.blur(input);

      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      expect(invoke).toHaveBeenCalledWith('submit_table_changes', expect.objectContaining({
        updates: expect.arrayContaining([
          expect.objectContaining({
            pkValue: '1',
            values: expect.arrayContaining([
              expect.objectContaining({ column: 'name', value: 'Alicia' }),
            ]),
          }),
        ]),
      }));
    });

    it('deleted row is excluded from updates even if also modified', async () => {
      vi.mocked(invoke).mockResolvedValueOnce(undefined);
      mockedUseTableData.mockReturnValue({ ...defaultTableDataReturn, columnKeys: pkColumnKeys });
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);

      // Modify cell
      const aliceCell = screen.getByText('Alice').closest('td')!;
      fireEvent.click(aliceCell);
      fireEvent.doubleClick(aliceCell);
      const input = aliceCell.querySelector('input')!;
      fireEvent.change(input, { target: { value: 'Alicia' } });
      fireEvent.blur(input);

      // Then select the row and delete it
      const indexCells = screen.getAllByTitle(/Click to select/);
      fireEvent.click(indexCells[0]);
      fireEvent.click(screen.getByTitle('Mark 1 row(s) for deletion'));

      await act(async () => {
        fireEvent.click(screen.getByTitle('Submit all changes'));
      });

      const call = vi.mocked(invoke).mock.calls[0];
      const args = call[1] as { updates: unknown[] };
      expect(args.updates).toHaveLength(0);
    });
  });

  describe('click outside behavior', () => {
    it('mousedown outside closes the filter modal (covers line 121)', () => {
      mockedUseTableFilters.mockReturnValue({
        ...defaultFiltersReturn,
        openFilterCol: 'name',
      } as ReturnType<typeof useTableFilters>);
      render(<DataTable {...defaultProps()} />);
      fireEvent.mouseDown(document.body);
      expect(defaultFiltersReturn.closeFilter).toHaveBeenCalled();
    });

    it('mousedown outside closes the columns popover (covers line 124)', () => {
      render(<DataTable {...defaultProps()} />);
      fireEvent.click(screen.getByText('Columns'));
      expect(screen.getAllByRole('checkbox').length).toBeGreaterThan(0);
      fireEvent.mouseDown(document.body);
      expect(screen.queryAllByRole('checkbox')).toHaveLength(0);
    });
  });

  describe('onApplyFilter via FilterModal Apply button', () => {
    it('clicking Apply in FilterModal calls applyFilter and onPromote (covers lines 293-294)', () => {
      const onPromote = vi.fn();
      mockedUseTableFilters.mockReturnValue({
        ...defaultFiltersReturn,
        openFilterCol: 'name',
        filterDraft: { value: 'test', value2: '', operator: 'eq' as const, caseSensitive: false, nullFilter: '' as const },
      } as ReturnType<typeof useTableFilters>);
      render(<DataTable {...defaultProps({ onPromote })} />);
      fireEvent.click(screen.getByText('Apply'));
      expect(defaultFiltersReturn.applyFilter).toHaveBeenCalledWith('name', 'text');
      expect(onPromote).toHaveBeenCalledTimes(1);
    });
  });

  describe('DropColumnModal via context menu', () => {
    it('right-clicking column header triggers onDropColumn and opens modal (covers line 404)', async () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const nameHeader = screen.getByText('name').closest('th')!;
      fireEvent.contextMenu(nameHeader);
      const dropItem = await screen.findByText('Drop Column');
      fireEvent.click(dropItem);
      expect(screen.getByText(/This is irreversible/)).toBeInTheDocument();
    });

    it('Cancel button in DropColumnModal closes the modal (covers onCancel, line 622)', async () => {
      render(<DataTable {...defaultProps({ dbType: 'postgres' })} />);
      const nameHeader = screen.getByText('name').closest('th')!;
      fireEvent.contextMenu(nameHeader);
      const dropItem = await screen.findByText('Drop Column');
      fireEvent.click(dropItem);
      expect(screen.getByText(/This is irreversible/)).toBeInTheDocument();
      fireEvent.click(screen.getByRole('button', { name: /^cancel$/i }));
      expect(screen.queryByText(/This is irreversible/)).not.toBeInTheDocument();
    });

    it('dropping a column calls onDropped, onRefresh, onColumnDropped (covers line 621)', async () => {
      const onRefresh = vi.fn();
      const onColumnDropped = vi.fn();
      vi.mocked(invoke).mockResolvedValueOnce(undefined);
      render(<DataTable {...defaultProps({ dbType: 'postgres', onRefresh, onColumnDropped })} />);
      const nameHeader = screen.getByText('name').closest('th')!;
      fireEvent.contextMenu(nameHeader);
      const dropItem = await screen.findByText('Drop Column');
      fireEvent.click(dropItem);
      const confirmInput = screen.getByPlaceholderText('name');
      fireEvent.change(confirmInput, { target: { value: 'name' } });
      await act(async () => {
        fireEvent.click(screen.getByRole('button', { name: /^drop column$/i }));
      });
      expect(onRefresh).toHaveBeenCalled();
      expect(onColumnDropped).toHaveBeenCalled();
    });
  });
});
