import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import EditableCell from './EditableCell';

vi.mock('@/hooks/useSettings', () => ({
  useSettings: () => ({ settings: { dateFormat: 'iso' } }),
}));

function renderCell(props: Parameters<typeof EditableCell>[0]) {
  return render(
    <table>
      <tbody>
        <tr>
          <EditableCell {...props} />
        </tr>
      </tbody>
    </table>,
  );
}

function defaultProps(overrides: Partial<Parameters<typeof EditableCell>[0]> = {}) {
  return {
    cell: 'Alice',
    colName: 'name',
    colWidth: undefined,
    rowIdx: 0,
    colIdx: 0,
    fkInfo: undefined,
    colType: 'text' as const,
    searchQuery: '',
    renderCellContent: (text: string) => text,
    onNavigateFk: undefined,
    editable: true,
    isModified: false,
    isDeleted: false,
    modifiedValue: undefined,
    onModify: vi.fn(),
    isActive: false,
    isEditing: false,
    onActivate: vi.fn(),
    onStartEdit: vi.fn(),
    onStopEdit: vi.fn(),
    onNavigate: vi.fn(),
    onRevert: undefined,
    onCopy: undefined,
    ...overrides,
  };
}

beforeEach(() => vi.clearAllMocks());

describe('EditableCell', () => {
  describe('display mode', () => {
    it('shows italic "null" when cell is null', () => {
      renderCell(defaultProps({ cell: null }));
      expect(screen.getByText('null')).toHaveClass('italic');
    });

    it('shows cell string value', () => {
      renderCell(defaultProps({ cell: 'Alice' }));
      expect(screen.getByText('Alice')).toBeInTheDocument();
    });

    it('shows modified value when isModified and modifiedValue set', () => {
      renderCell(defaultProps({ isModified: true, modifiedValue: 'Bob', cell: 'Alice' }));
      expect(screen.getByText('Bob')).toBeInTheDocument();
    });

    it('shows FK navigate button when fkInfo has fkRefTable and cell is not null', () => {
      renderCell(
        defaultProps({
          cell: '1',
          fkInfo: {
            columnName: 'id',
            fkRefTable: 'orders',
            fkRefColumn: 'user_id',
            isPrimary: false,
            isAutoGenerated: false,
            isNullable: true,
          },
          onNavigateFk: vi.fn(),
          isModified: false,
        }),
      );
      expect(screen.getByTitle('Navigate to orders.user_id')).toBeInTheDocument();
    });

    it('does not show FK button when cell is null', () => {
      renderCell(
        defaultProps({
          cell: null,
          fkInfo: {
            columnName: 'id',
            fkRefTable: 'orders',
            fkRefColumn: 'user_id',
            isPrimary: false,
            isAutoGenerated: false,
            isNullable: true,
          },
          onNavigateFk: vi.fn(),
        }),
      );
      expect(screen.queryByTitle(/Navigate to/)).not.toBeInTheDocument();
    });
  });

  describe('editing mode — input types', () => {
    it('renders <input> for text colType when isEditing=true', () => {
      renderCell(defaultProps({ isEditing: true, colType: 'text' }));
      expect(screen.getByRole('textbox')).toBeInTheDocument();
    });

    it('renders number input for number colType', () => {
      renderCell(defaultProps({ isEditing: true, colType: 'number', cell: '42' }));
      const input = screen.getByRole('spinbutton');
      expect(input).toBeInTheDocument();
    });

    it('renders <select> for boolean colType', () => {
      renderCell(defaultProps({ isEditing: true, colType: 'boolean' }));
      expect(screen.getByRole('combobox')).toBeInTheDocument();
    });

    it('boolean select includes NULL option when isNullable', () => {
      renderCell(
        defaultProps({
          isEditing: true,
          colType: 'boolean',
          fkInfo: {
            columnName: 'active',
            fkRefTable: null,
            fkRefColumn: null,
            isPrimary: false,
            isAutoGenerated: false,
            isNullable: true,
          },
        }),
      );
      expect(screen.getByRole('option', { name: 'NULL' })).toBeInTheDocument();
    });

    it('boolean select has no NULL option when not nullable', () => {
      renderCell(
        defaultProps({
          isEditing: true,
          colType: 'boolean',
          fkInfo: {
            columnName: 'active',
            fkRefTable: null,
            fkRefColumn: null,
            isPrimary: false,
            isAutoGenerated: false,
            isNullable: false,
          },
        }),
      );
      expect(screen.queryByRole('option', { name: 'NULL' })).not.toBeInTheDocument();
    });

    it('blur on input calls commitEdit (calls onModify + onStopEdit)', () => {
      const onModify = vi.fn();
      const onStopEdit = vi.fn();
      renderCell(defaultProps({ isEditing: true, onModify, onStopEdit }));
      fireEvent.blur(screen.getByRole('textbox'));
      expect(onModify).toHaveBeenCalledTimes(1);
      expect(onStopEdit).toHaveBeenCalledTimes(1);
    });
  });

  describe('keyboard when editing', () => {
    function renderEditing(overrides: Partial<Parameters<typeof EditableCell>[0]> = {}) {
      const props = defaultProps({ isEditing: true, isActive: true, ...overrides });
      renderCell(props);
      return props;
    }

    it('Escape calls cancelEdit (onStopEdit)', () => {
      const onStopEdit = vi.fn();
      renderEditing({ onStopEdit });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Escape' });
      expect(onStopEdit).toHaveBeenCalledTimes(1);
    });

    it('Enter calls commitEdit + onNavigate("down")', () => {
      const onModify = vi.fn();
      const onStopEdit = vi.fn();
      const onNavigate = vi.fn();
      renderEditing({ onModify, onStopEdit, onNavigate });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Enter' });
      expect(onModify).toHaveBeenCalledTimes(1);
      expect(onNavigate).toHaveBeenCalledWith('down');
    });

    it('Tab calls commitEdit + onNavigate("right")', () => {
      const onModify = vi.fn();
      const onStopEdit = vi.fn();
      const onNavigate = vi.fn();
      renderEditing({ onModify, onStopEdit, onNavigate });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Tab' });
      expect(onNavigate).toHaveBeenCalledWith('right');
    });

    it('Shift+Tab calls commitEdit + onNavigate("left")', () => {
      const onModify = vi.fn();
      const onStopEdit = vi.fn();
      const onNavigate = vi.fn();
      renderEditing({ onModify, onStopEdit, onNavigate });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Tab', shiftKey: true });
      expect(onNavigate).toHaveBeenCalledWith('left');
    });

    it('Ctrl+Delete when nullable calls onModify(null) + onStopEdit', () => {
      const onModify = vi.fn();
      const onStopEdit = vi.fn();
      renderEditing({ onModify, onStopEdit });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Delete', ctrlKey: true });
      expect(onModify).toHaveBeenCalledWith(null);
      expect(onStopEdit).toHaveBeenCalled();
    });

    it('Ctrl+Backspace when nullable calls onModify(null)', () => {
      const onModify = vi.fn();
      const onStopEdit = vi.fn();
      renderEditing({ onModify, onStopEdit });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Backspace', ctrlKey: true });
      expect(onModify).toHaveBeenCalledWith(null);
    });

    it('Ctrl+Delete when not nullable does NOT call onModify', () => {
      const onModify = vi.fn();
      renderEditing({
        onModify,
        fkInfo: {
          columnName: 'name',
          fkRefTable: null,
          fkRefColumn: null,
          isPrimary: false,
          isAutoGenerated: false,
          isNullable: false,
        },
      });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Delete', ctrlKey: true });
      expect(onModify).not.toHaveBeenCalledWith(null);
    });
  });

  describe('keyboard when active (not editing)', () => {
    function renderActive(overrides: Partial<Parameters<typeof EditableCell>[0]> = {}) {
      renderCell(defaultProps({ isActive: true, isEditing: false, ...overrides }));
    }

    it('Enter starts edit when editable and not deleted', () => {
      const onStartEdit = vi.fn();
      renderActive({ onStartEdit });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Enter' });
      expect(onStartEdit).toHaveBeenCalledTimes(1);
    });

    it('F2 starts edit when editable and not deleted', () => {
      const onStartEdit = vi.fn();
      renderActive({ onStartEdit });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'F2' });
      expect(onStartEdit).toHaveBeenCalledTimes(1);
    });

    it('Enter does not start edit when not editable', () => {
      const onStartEdit = vi.fn();
      renderActive({ onStartEdit, editable: false });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Enter' });
      expect(onStartEdit).not.toHaveBeenCalled();
    });

    it('Enter does not start edit when isDeleted=true', () => {
      const onStartEdit = vi.fn();
      renderActive({ onStartEdit, isDeleted: true });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Enter' });
      expect(onStartEdit).not.toHaveBeenCalled();
    });

    it.each([
      ['ArrowUp', 'up'],
      ['ArrowDown', 'down'],
      ['ArrowLeft', 'left'],
      ['ArrowRight', 'right'],
    ])('%s calls onNavigate("%s")', (key, dir) => {
      const onNavigate = vi.fn();
      renderActive({ onNavigate });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key });
      expect(onNavigate).toHaveBeenCalledWith(dir);
    });

    it('Tab calls onNavigate("right")', () => {
      const onNavigate = vi.fn();
      renderActive({ onNavigate });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Tab' });
      expect(onNavigate).toHaveBeenCalledWith('right');
    });

    it('Shift+Tab calls onNavigate("left")', () => {
      const onNavigate = vi.fn();
      renderActive({ onNavigate });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Tab', shiftKey: true });
      expect(onNavigate).toHaveBeenCalledWith('left');
    });

    it('Delete key with nullable calls onModify(null)', () => {
      const onModify = vi.fn();
      renderActive({ onModify });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Delete' });
      expect(onModify).toHaveBeenCalledWith(null);
    });

    it('Delete key without nullable does NOT call onModify', () => {
      const onModify = vi.fn();
      renderActive({
        onModify,
        fkInfo: {
          columnName: 'name',
          fkRefTable: null,
          fkRefColumn: null,
          isPrimary: false,
          isAutoGenerated: false,
          isNullable: false,
        },
      });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'Delete' });
      expect(onModify).not.toHaveBeenCalled();
    });

    it('printable character starts edit and sets draft', () => {
      const onStartEdit = vi.fn();
      renderActive({ onStartEdit });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'a' });
      expect(onStartEdit).toHaveBeenCalledTimes(1);
    });

    it('printable char does not start edit when not editable', () => {
      const onStartEdit = vi.fn();
      renderActive({ onStartEdit, editable: false });
      const cell = document.querySelector('td')!;
      fireEvent.keyDown(cell, { key: 'a' });
      expect(onStartEdit).not.toHaveBeenCalled();
    });
  });

  describe('mouse interactions', () => {
    it('click when not active calls onActivate', () => {
      const onActivate = vi.fn();
      renderCell(defaultProps({ isActive: false, onActivate }));
      const cell = document.querySelector('td')!;
      fireEvent.click(cell);
      expect(onActivate).toHaveBeenCalledTimes(1);
    });

    it('click when already active does not call onActivate', () => {
      const onActivate = vi.fn();
      renderCell(defaultProps({ isActive: true, onActivate }));
      const cell = document.querySelector('td')!;
      fireEvent.click(cell);
      expect(onActivate).not.toHaveBeenCalled();
    });

    it('double-click (editable, not deleted) calls onActivate + onStartEdit', () => {
      const onActivate = vi.fn();
      const onStartEdit = vi.fn();
      renderCell(defaultProps({ onActivate, onStartEdit }));
      const cell = document.querySelector('td')!;
      fireEvent.dblClick(cell);
      expect(onActivate).toHaveBeenCalledTimes(1);
      expect(onStartEdit).toHaveBeenCalledTimes(1);
    });

    it('double-click when isDeleted does NOT call onStartEdit', () => {
      const onStartEdit = vi.fn();
      renderCell(defaultProps({ onStartEdit, isDeleted: true }));
      const cell = document.querySelector('td')!;
      fireEvent.dblClick(cell);
      expect(onStartEdit).not.toHaveBeenCalled();
    });

    it('context menu activates when not active', () => {
      const onActivate = vi.fn();
      renderCell(defaultProps({ isActive: false, onActivate }));
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      expect(onActivate).toHaveBeenCalledTimes(1);
    });

    it('context menu does not call onActivate when already active', () => {
      const onActivate = vi.fn();
      renderCell(defaultProps({ isActive: true, onActivate }));
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      expect(onActivate).not.toHaveBeenCalled();
    });
  });

  describe('context menu items', () => {
    it('Copy item calls navigator.clipboard.writeText with displayStr', () => {
      const writeText = vi.fn().mockResolvedValue(undefined);
      Object.defineProperty(navigator, 'clipboard', {
        value: { writeText },
        writable: true,
        configurable: true,
      });
      renderCell(defaultProps({ cell: 'Alice' }));
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      const copyItem = screen.getByText('Copy');
      fireEvent.click(copyItem);
      expect(writeText).toHaveBeenCalledWith('Alice');
    });

    it('Edit item calls onActivate + onStartEdit', () => {
      const onActivate = vi.fn();
      const onStartEdit = vi.fn();
      renderCell(defaultProps({ onActivate, onStartEdit, editable: true, isDeleted: false }));
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      const editItem = screen.getByText('Edit');
      fireEvent.click(editItem);
      expect(onActivate).toHaveBeenCalled();
      expect(onStartEdit).toHaveBeenCalled();
    });

    it('Set NULL item calls onModify(null)', () => {
      const onModify = vi.fn();
      renderCell(
        defaultProps({
          onModify,
          editable: true,
          isDeleted: false,
          // fkInfo defaults → isNullable = true since fkInfo is undefined → isNullable = fkInfo?.isNullable ?? true
        }),
      );
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      const setNullItem = screen.getByText('Set NULL');
      fireEvent.click(setNullItem);
      expect(onModify).toHaveBeenCalledWith(null);
    });

    it('Revert item calls onRevert', () => {
      const onRevert = vi.fn();
      renderCell(
        defaultProps({
          onRevert,
          isModified: true,
          modifiedValue: 'Bob',
          editable: true,
          isDeleted: false,
        }),
      );
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      const revertItem = screen.getByText('Revert');
      fireEvent.click(revertItem);
      expect(onRevert).toHaveBeenCalledTimes(1);
    });

    it('Edit item not shown when not editable', () => {
      renderCell(defaultProps({ editable: false }));
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      expect(screen.queryByText('Edit')).not.toBeInTheDocument();
    });

    it('Set NULL not shown when not nullable', () => {
      renderCell(
        defaultProps({
          editable: true,
          isDeleted: false,
          fkInfo: {
            columnName: 'name',
            fkRefTable: null,
            fkRefColumn: null,
            isPrimary: false,
            isAutoGenerated: false,
            isNullable: false,
          },
        }),
      );
      const cell = document.querySelector('td')!;
      fireEvent.contextMenu(cell);
      expect(screen.queryByText('Set NULL')).not.toBeInTheDocument();
    });
  });

  describe('display styling', () => {
    it('applies modified background class when isModified and not deleted', () => {
      const { container } = renderCell(
        defaultProps({ isModified: true, isDeleted: false, modifiedValue: 'new' }),
      );
      const td = container.querySelector('td')!;
      expect(td.className).toContain('bg-blue-50');
    });

    it('applies active outline class when isActive', () => {
      const { container } = renderCell(defaultProps({ isActive: true }));
      const td = container.querySelector('td')!;
      expect(td.className).toContain('outline-primary');
    });

    it('FK navigate button calls onNavigateFk when clicked', () => {
      const onNavigateFk = vi.fn();
      renderCell(
        defaultProps({
          cell: '42',
          fkInfo: {
            columnName: 'user_id',
            fkRefTable: 'users',
            fkRefColumn: 'id',
            isPrimary: false,
            isAutoGenerated: false,
            isNullable: true,
          },
          onNavigateFk,
          isModified: false,
        }),
      );
      const fkBtn = screen.getByTitle('Navigate to users.id');
      fireEvent.click(fkBtn);
      expect(onNavigateFk).toHaveBeenCalledWith('users', 'id', '42', 'text');
    });
  });
});
